apiVersion: v1
kind: Pod
metadata:
  name: my-init-container
  namespace: ns1
  labels:
    app: my-init-container
spec:
  initContainers:
    - name: my-init-container
      image: busybox
      command: ['sh', '-c', 'sleep 10;  echo Hello from the init container!']
  containers:
    - name: my-httpd
      image: httpd
      ports:
        - containerPort: 80