apiVersion: v1
kind: Pod
metadata:
  name: my-init-container-with-service
  namespace: ns1
  labels:
    app: my-init-container-with-service
spec:
  initContainers:
    - name: my-init-container
      image: busybox
      command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
  containers:
    - name: my-httpd
      image: httpd
      ports:
        - containerPort: 80