apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-httpd-rs
  namespace: ns1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-httpd-app
  template:
    metadata:
      labels:
        app: my-httpd-app
    spec:
      containers:
        - name: my-httpd
          image: mkurambhatti/myapp
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-httpd-service
  namespace: ns1
spec:
  type: NodePort
  selector:
    app: my-httpd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080