apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: ns1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-http-container
          image: httpd
          ports:
            - containerPort: 80