apiVersion : v1
kind: Pod
metadata:
  name: my-pod
  namespace: ns1
  labels:
    app: myapp
spec:
  containers:
    - name: my-httpd-container
      image: httpd
      ports:
        - containerPort: 80