apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: ns1
  name: my-replica-set
  labels:
    app: myReplicaSetApp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: httpd-container
        image: httpd
        ports:
        - containerPort: 80