apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: ns1
type: Opaque
data:
  username : cm9vdA==
  password : cm9vdA==
  ACCESS_KEY : YWNjZXNzX2tleQ==
  SECRET_KEY : c2VjcmV0X2tleQ==
  DB_PASSWORD : cGFzc3dvcmQ=
  DB_USERNAME : dXNlcm5hbWU=
  DB_NAME : ZGF0YWJhc2U=

---
apiVersion: v1
kind: Pod
metadata:
  name: my-http-pod-with-secret
  namespace: ns1
spec:
  containers:
    - name: my-http-container
      image: httpd
      ports:
        - containerPort: 80
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: ACCESS_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_NAME
        - name: USERNAME
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:  
            secretKeyRef:
              name: my-secret
              key: password
