apiVersion: v1

kind: Pod

metadata:
  namespace: ns1
  name: multi-container-pod-with-label
  labels:
    app: myMultiPodApp

spec:
  containers:
  - name: httpd-container
    image: httpd
    ports:
    - containerPort: 80
  - name: mongo-container
    image: mongo
    ports:
    - containerPort: 27017