apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
  namespace: ns1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
        - name: my-website-container
          image: mkurambhatti/website:latest
          ports:
            - containerPort: 80
              protocol: TCP