FROM httpd
COPY ./index.html /usr/local/apache2/htdocs/

EXPOSE 80

# Use below commands to build and push the Docker image
# docker image build -t mkurambhatti/website .
# docker image push mkurambhatti/website:latest