apiVersion: v1
kind: Service
metadata:
  name: my-website-service
  namespace: ns1
spec:
  selector:
    app: mywebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort