apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: ns1
data:
  backend-url : "http://my-backend-service:8080"
  PORT : "8080"

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-with-configmap
  namespace: ns1
spec:
  containers:
    - name: my-http-container
      image: httpd
      ports:
        - containerPort: 8080
      env:
        - name: APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: backend-url
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: PORT